package com.example.vitazen.util

object RandomNames {
    val list = listOf(
        "Bé Mây",
        "Bé Nắng",
        "Bé Gió",
        "Bé Mèo",
        "Bé Sóc",
        "Bé Cún",
        "Bé Thỏ",
        "Bé Cừu",
        "Bé Gấu",
        "Bé Heo",
        "Bé Nai",
        "Bé Cá",
        "Bé Bắp",
        "Bé Cam",
        "Bé Dâu",
        "Bé Sữa",
        "Bé Mít",
        "Bé Xoài",
        "Bé Chuối",
        "Bé Mầm",
        "Bé Lá",
        "Bé Mơ",
        "Bé Mật",
        "Bé Mít Ướt",
        "Bé Kem",
        "Bé Bánh",
        "Bé Sương",
        "Bé Mực",
        "Bé Tí",
        "Bé Tũn",
        "Bé Tép",
        "Bé Tôm",
        "Bé Tí Hon",
        "Bé Cỏ",
        "Bé Mèo Con",
        "Bé Sóc Nhí",
        "Bé Gấu Bông",
        "Bé Heo Con",
        "Bé Thỏ Trắng",
        "Bé Cừu Non",
        "Bé Gà",
        "Bé Vịt",
        "Bé Ong",
        "Bé Bướm",
        "Bé Cá Vàng",
        "Bé Cá Heo",
        "Bé Chim",
        "Bé Sâu",
        "Bé Ốc",
        "Bé Sò",
        "Bé Kem Dâu",
        "Bé Bánh Bao",
        "Bé Bánh Mì",
        "Bé Sữa Chua",
        "Bé Sữa Tươi",
        "Bé Bắp Rang",
        "Bé Bắp Cải",
        "Bé Cà Rốt",
        "Bé Khoai",
        "Bé Đậu",
        "Bé Đậu Đỏ",
        "Bé Đậu Xanh",
        "Bé Đậu Nành",
        "Bé Dưa",
        "Bé Dưa Hấu",
        "Bé Dưa Leo",
        "Bé Táo",
        "Bé Lê",
        "Bé Nho",
        "Bé Cam Sành",
        "Bé Quýt",
        "Bé Chanh",
        "Bé Chanh Leo",
        "Bé Mận",
        "Bé Mận Hồng",
        "Bé Mận Đỏ",
        "Bé Mận Xanh"
    )
}
